[package]
name = "libxinux-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
signal-hook = "0.3.17"
users = "0.11.0"

[[bin]]
name = "libxinux-helper"
path = "src/main.rs"
